version: "2"

run:
  timeout: 3m

linters:
  enable:
    - govet
    - gocyclo
    - goconst
    - misspell
    - funlen
    - godox
    - errcheck
    - gocritic
    - staticcheck
    - ineffassign
    - unused
