version: "2"

run:
  timeout: 3m

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 12
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME
  depguard:
    rules:
      main:
        files:
          - $all
        allow:
          - $gostd
          - github.com/taskmedia/ddns-allowlist
      testify:
        files:
          - "$test"
        allow:
          - $gostd
          - github.com/stretchr/testify/assert
          - github.com/stretchr/testify/require
          - github.com/taskmedia/ddns-allowlist

linters:
  enable:
    - govet
    - gocyclo
    - goconst
    - misspell
    - funlen
    - godox
    - depguard
    - errcheck
    - gocritic
    - staticcheck
    - ineffassign
    - unused
